// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaEQHOaiZwcXHbdXndFE10qfXpNx27P-o',
    appId: '1:456787216200:web:df54de52a89aeb1949557d',
    messagingSenderId: '456787216200',
    projectId: 'food-babies',
    authDomain: 'food-babies.firebaseapp.com',
    storageBucket: 'food-babies.appspot.com',
    measurementId: 'G-N0HP4NSMV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHmO_wIGgwdzn1o8UIVi5H8bydhPLaLA',
    appId: '1:456787216200:android:fcf110a9bfda6e7b49557d',
    messagingSenderId: '456787216200',
    projectId: 'food-babies',
    storageBucket: 'food-babies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5To6gR-mZ7SQVN6fu1XmT4AvajmTHUw0',
    appId: '1:456787216200:ios:3a3be526260ccb3249557d',
    messagingSenderId: '456787216200',
    projectId: 'food-babies',
    storageBucket: 'food-babies.appspot.com',
    androidClientId: '456787216200-e9a9686hl8875ja3htjcb6k3ghe8dskr.apps.googleusercontent.com',
    iosClientId: '456787216200-e3ac2lf6h9if4nnblnh29pcg687as4mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodBabies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5To6gR-mZ7SQVN6fu1XmT4AvajmTHUw0',
    appId: '1:456787216200:ios:3a3be526260ccb3249557d',
    messagingSenderId: '456787216200',
    projectId: 'food-babies',
    storageBucket: 'food-babies.appspot.com',
    androidClientId: '456787216200-e9a9686hl8875ja3htjcb6k3ghe8dskr.apps.googleusercontent.com',
    iosClientId: '456787216200-e3ac2lf6h9if4nnblnh29pcg687as4mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodBabies',
  );
}
